### PR TITLE
Misprint correction on README.md, second try

### PR DESCRIPTION
**Pull request by severin31**
(I'm still learning git and github, I hope I don't make a mistake)

### CODE REVIEW

**Comment by richrd** [comment]
Hi! Great that you're learning git, and I really appreciate your pull request :). Congratulations on your first contribution!

You haven't made any mistakes, but I usually only merge new versions of Suplemon to the master branch. I develop the software in the dev branch, and when I release a new version I put it in the master branch. That way the master branch always has a working version that people can use.

If you could change the pull request so that it will merge to `richrd:dev`, that would be great :+1: Then I'll merge it straight away.

**Comment by richrd** [comment]
Since this PR wasn't big, I merged it into the master branch. Thanks a lot, nice to have you as a contributor on my project :)

**Comment by severin31** [comment]
Oh. Sorry. I wasn't quick enough this time. But I understand now that some project use dev branch first, thanks. And thanks for your very nice project!!! I'm still learning java but i should have learn python first.

**Comment by richrd** [comment]
No problem :) I think java and python are both good for different things. BTW are you actively using Suplemon?

**Pull request merged**
