### PR TITLE
Add missing dependency wcwidth

### PR DESCRIPTION
**Pull request by bagage**

### CODE REVIEW

**Comment by richrd** [comment]
Seems to me that this is unnecessary. The `requirements-dev.txt` is only for dependencies that are required while developing or testing suplemon. The run time dependencies are specified in setup.py here: https://github.com/richrd/suplemon/blob/master/setup.py#L24

**Comment by bagage** [comment]
Oops, my bad. Indeed I just blindly copied the README instructions but I should have run `setup.py install` instead of running suplemon directly. Can close indeed!

**Comment by richrd** [comment]
Sure, no problem and I really appreciate your participation! :)

**Comment by richrd** [comment]
To be honest I do want suplemon to work when running directly from source, and if it doesn't I've violated what I've written in the readme. I might add a dummy fallback for wcwidth, but that's a bit unreliable. I'll keep this in mind and see what I can do about it.

**Pull request closed without merging**
