### PR TITLE
Update cursor.py to use namedtuple

### PR DESCRIPTION
**Pull request by eugene-eeo**
With this change the need to implement custom ``__getitem__`` and other magic friends are no longer needed since the tuple class already handles that for us. The original API is preserved.

### CODE REVIEW

**Comment by eugene-eeo** [comment]
@richrd also if you want to do something like ``Cursor(Cursor(x,y))`` it is better that you unpack the tuple using a "star", e.g. ``Cursor(*Cursor(x,y))`` or ``Cursor(*(x,y))``. It works on any iterable and has the bonus that the custom logic in ``__new__`` is no longer required.

**Comment by richrd** [comment]
Thanks very much! Looks very good, but namedtuple doesn't seem to support setting attributes. I do this a lot in the editor code to manipulate the cursors. Later I'm going to add proper methods for different cursor manipulations.
Anyway I guess namedlist could be used instead of namedtuple. What do you think?

**Comment by eugene-eeo** [comment]
IMHO setting custom or arbitrary attributes on objects is quite "dangerous" so it's better to add proper methods as you've said. That being said, if some state really needs to be kept in the Cursor object itself you can always add your own ``__getattr__`` and ``__setattr__`` magic, though it's better to pass values around rather than store them in the Cursor object.

**Comment by richrd** [comment]
What do you mean by "better to pass values around rather than store them in the Cursor object."? Do you mean that the access should only be done via methods? Basically I only need the x and y values stored in Cursor (maybe others in the future), and I need them to be mutable somehow. To me, it seems like namedtuple is always immutable. (?)

Anyway I'll work on the Cursor implementation asap. Thanks a lot for your contributions! :+1:

**Comment by eugene-eeo** [comment]
Oh sorry, I thought you wanted to set arbitrary attributes on the Cursor. My bad!

I'm not too familiar with the innards but perhaps making the cursor object a namedtuple will force you to make the code more functional, I.e. immutable. If you go down that path I recommend adding:

```python
Cursor.move(x,y) -> Cursor(self.x+x, self.y+y)
```

And perhaps storing a few cursors in a stack to keep track of their histories.

**Comment by richrd** [comment]
Since the current editor code needs cursor mutability in almost all operations, it would be a lot of work to change the logic entirely. For that reason I'll close this for now.

However I'm going to implement better methods for the Cursor object and use them in the editor code. I'm also going to try to simplify the editor code and make it more functional and understandable. Along the way I'll also define and implement the APIs for extensions.

Thanks for the suggestion and input! I appreciate it a lot :+1:

**Pull request closed without merging**
