### PR TITLE
Patched up various one-offs

### PR DESCRIPTION
**Pull request by twolfson**
On occasion, I have been exploring testing options for `ncurses` and Suplemon in general. Today, I wound up wanting to see if there were any other options for testing. While re-reading parts of the repo, I found some one-offs that would be good to fix up. This PR is a collection of all of them.

In this PR:

- [x] Reduced greed of version regexp in `setup.py`
    - By using a character class, we remove the need for backtracking after the `.*` consumes the quote
    - Here's a good reference site: https://www.loggly.com/blog/five-invaluable-techniques-to-improve-regex-performance/
- [x] Fixed README heading to use proper casing of Suplemon (used eveywhere else)
- [x] Fixed Linux casing in README
- [x] Added installation instructions for "Optional dependencies" in README
- [x] Formalized `.travis.yml` steps into `requirements-dev.txt` and `./test.sh` so it can be reused locally
- [x] Added "Development" instructions in README
- [x] Trimmed trailing whitespace in README (kept on making noise in `git add -p` for me)
- [x] Fixed up single quotes to double quotes for consistency
    - Waiting on https://github.com/zheller/flake8-quotes/pull/9 to actually enforce this

**Notes:**

With respect to testing, I have a few thoughts in my head. The gist is we shouldn't test anything that is going to change when aligning with the Sublime Text API (or at least not too thoroughly) (e.g cursors instead of regions). This is to prevent creating excess work that is getting thrown out. I will create a more formal issue for discussion later.

### CODE REVIEW

**Comment by richrd** [comment]
Many thanks! I'll check this out and merge as soon as I have time.

One note though, any chance you could change the target to richrd:dev, instead of the master? I try to only update the master with new versions.

**Comment by twolfson** [comment]
Ah, sure thing. I will need to open a new PR for that but can do.

**Comment by richrd** [comment]
Done. Added to version 0.1.40 :+1:

**Comment by twolfson** [comment]
:tada:

**Pull request closed without merging**
